export interface Flag {
  name: string;
  emoji: string;
  code: string;
}

export const flags: Flag[] = [
  { name: "Afghanistan", emoji: "🇦🇫", code: "af" },
  { name: "Albania", emoji: "🇦🇱", code: "al" },
  { name: "Algeria", emoji: "🇩🇿", code: "dz" },
  { name: "Andorra", emoji: "🇦🇩", code: "ad" },
  { name: "Angola", emoji: "🇦🇴", code: "ao" },
  { name: "Argentina", emoji: "🇦🇷", code: "ar" },
  { name: "Armenia", emoji: "🇦🇲", code: "am" },
  { name: "Australia", emoji: "🇦🇺", code: "au" },
  { name: "Austria", emoji: "🇦🇹", code: "at" },
  { name: "Azerbaijan", emoji: "🇦🇿", code: "az" },
  { name: "Bahamas", emoji: "🇧🇸", code: "bs" },
  { name: "Bahrain", emoji: "🇧🇭", code: "bh" },
  { name: "Bangladesh", emoji: "🇧🇩", code: "bd" },
  { name: "Belarus", emoji: "🇧🇾", code: "by" },
  { name: "Belgium", emoji: "🇧🇪", code: "be" },
  { name: "Bolivia", emoji: "🇧🇴", code: "bo" },
  { name: "Bosnia", emoji: "🇧🇦", code: "ba" },
  { name: "Botswana", emoji: "🇧🇼", code: "bw" },
  { name: "Brazil", emoji: "🇧🇷", code: "br" },
  { name: "Bulgaria", emoji: "🇧🇬", code: "bg" },
  { name: "Cambodia", emoji: "🇰🇭", code: "kh" },
  { name: "Cameroon", emoji: "🇨🇲", code: "cm" },
  { name: "Canada", emoji: "🇨🇦", code: "ca" },
  { name: "Chile", emoji: "🇨🇱", code: "cl" },
  { name: "China", emoji: "🇨🇳", code: "cn" },
  { name: "Colombia", emoji: "🇨🇴", code: "co" },
  { name: "Costa Rica", emoji: "🇨🇷", code: "cr" },
  { name: "Croatia", emoji: "🇭🇷", code: "hr" },
  { name: "Cuba", emoji: "🇨🇺", code: "cu" },
  { name: "Cyprus", emoji: "🇨🇾", code: "cy" },
  { name: "Czechia", emoji: "🇨🇿", code: "cz" },
  { name: "Denmark", emoji: "🇩🇰", code: "dk" },
  { name: "Dominican Republic", emoji: "🇩🇴", code: "do" },
  { name: "Ecuador", emoji: "🇪🇨", code: "ec" },
  { name: "Egypt", emoji: "🇪🇬", code: "eg" },
  { name: "El Salvador", emoji: "🇸🇻", code: "sv" },
  { name: "Estonia", emoji: "🇪🇪", code: "ee" },
  { name: "Ethiopia", emoji: "🇪🇹", code: "et" },
  { name: "Finland", emoji: "🇫🇮", code: "fi" },
  { name: "France", emoji: "🇫🇷", code: "fr" },
  { name: "Georgia", emoji: "🇬🇪", code: "ge" },
  { name: "Germany", emoji: "🇩🇪", code: "de" },
  { name: "Ghana", emoji: "🇬🇭", code: "gh" },
  { name: "Greece", emoji: "🇬🇷", code: "gr" },
  { name: "Guatemala", emoji: "🇬🇹", code: "gt" },
  { name: "Honduras", emoji: "🇭🇳", code: "hn" },
  { name: "Hungary", emoji: "🇭🇺", code: "hu" },
  { name: "Iceland", emoji: "🇮🇸", code: "is" },
  { name: "India", emoji: "🇮🇳", code: "in" },
  { name: "Indonesia", emoji: "🇮🇩", code: "id" },
  { name: "Iran", emoji: "🇮🇷", code: "ir" },
  { name: "Iraq", emoji: "🇮🇶", code: "iq" },
  { name: "Ireland", emoji: "🇮🇪", code: "ie" },
  { name: "Israel", emoji: "🇮🇱", code: "il" },
  { name: "Italy", emoji: "🇮🇹", code: "it" },
  { name: "Jamaica", emoji: "🇯🇲", code: "jm" },
  { name: "Japan", emoji: "🇯🇵", code: "jp" },
  { name: "Jordan", emoji: "🇯🇴", code: "jo" },
  { name: "Kazakhstan", emoji: "🇰🇿", code: "kz" },
  { name: "Kenya", emoji: "🇰🇪", code: "ke" },
  { name: "Kuwait", emoji: "🇰🇼", code: "kw" },
  { name: "Latvia", emoji: "🇱🇻", code: "lv" },
  { name: "Lebanon", emoji: "🇱🇧", code: "lb" },
  { name: "Lithuania", emoji: "🇱🇹", code: "lt" },
  { name: "Luxembourg", emoji: "🇱🇺", code: "lu" },
  { name: "Malaysia", emoji: "🇲🇾", code: "my" },
  { name: "Mexico", emoji: "🇲🇽", code: "mx" },
  { name: "Moldova", emoji: "🇲🇩", code: "md" },
  { name: "Morocco", emoji: "🇲🇦", code: "ma" },
  { name: "Netherlands", emoji: "🇳🇱", code: "nl" },
  { name: "New Zealand", emoji: "🇳🇿", code: "nz" },
  { name: "Nigeria", emoji: "🇳🇬", code: "ng" },
  { name: "North Macedonia", emoji: "🇲🇰", code: "mk" },
  { name: "Norway", emoji: "🇳🇴", code: "no" },
  { name: "Oman", emoji: "🇴🇲", code: "om" },
  { name: "Pakistan", emoji: "🇵🇰", code: "pk" },
  { name: "Panama", emoji: "🇵🇦", code: "pa" },
  { name: "Paraguay", emoji: "🇵🇾", code: "py" },
  { name: "Peru", emoji: "🇵🇪", code: "pe" },
  { name: "Philippines", emoji: "🇵🇭", code: "ph" },
  { name: "Poland", emoji: "🇵🇱", code: "pl" },
  { name: "Portugal", emoji: "🇵🇹", code: "pt" },
  { name: "Qatar", emoji: "🇶🇦", code: "qa" },
  { name: "Romania", emoji: "🇷🇴", code: "ro" },
  { name: "Saudi Arabia", emoji: "🇸🇦", code: "sa" },
  { name: "Serbia", emoji: "🇷🇸", code: "rs" },
  { name: "Singapore", emoji: "🇸🇬", code: "sg" },
  { name: "Slovakia", emoji: "🇸🇰", code: "sk" },
  { name: "Slovenia", emoji: "🇸🇮", code: "si" },
  { name: "South Africa", emoji: "🇿🇦", code: "za" },
  { name: "South Korea", emoji: "🇰🇷", code: "kr" },
  { name: "Spain", emoji: "🇪🇸", code: "es" },
  { name: "Sweden", emoji: "🇸🇪", code: "se" },
  { name: "Switzerland", emoji: "🇨🇭", code: "ch" },
  { name: "Thailand", emoji: "🇹🇭", code: "th" },
  { name: "Tunisia", emoji: "🇹🇳", code: "tn" },
  { name: "Turkey", emoji: "🇹🇷", code: "tr" },
  { name: "Ukraine", emoji: "🇺🇦", code: "ua" },
  { name: "United Arab Emirates", emoji: "🇦🇪", code: "ae" },
  { name: "United Kingdom", emoji: "🇬🇧", code: "gb" },
  { name: "United States", emoji: "🇺🇸", code: "us" },
  { name: "Uruguay", emoji: "🇺🇾", code: "uy" },
  { name: "Uzbekistan", emoji: "🇺🇿", code: "uz" },
  { name: "Venezuela", emoji: "🇻🇪", code: "ve" },
  { name: "Vietnam", emoji: "🇻🇳", code: "vn" },
  { name: "Zimbabwe", emoji: "🇿🇼", code: "zw" },
];

// Create a map for O(1) lookups
const flagMap = new Map(flags.map((flag) => [flag.code, flag]));

export function getFlagByCode(code: string): Flag | undefined {
  return flagMap.get(code.toLowerCase());
}

export function isValidFlagCode(code: string): boolean {
  return flagMap.has(code.toLowerCase());
}

export const validFlagCodes = new Set(flags.map((f) => f.code));
